import { useState, useMemo, useRef, useEffect, useCallback } from 'react';
import ReactDOM from 'react-dom';
import { RESET_HOUR_UTC } from './config/resetConfig';
import { submitResult } from './utils/submitResult';
// import pokemonData from '../data/pokemon_data.json';
// import titleImg from '../data/title.png';

// Load pokemonData and titleImg from public/data at runtime
function usePokemonData() {
  const [pokemonData, setPokemonData] = useState(null);
  useEffect(() => {
    let cancelled = false;
    fetch('data/pokemon_data.json')
      .then(res => res.json())
      .then(data => {
        if (!cancelled) {
          setPokemonData(data);
        }
      });
    return () => {
      cancelled = true;
    };
  }, []);
  return pokemonData;
}

// Load card manifest once at app level to avoid repeated network calls
function useCardManifest() {
  const [cardManifest, setCardManifest] = useState(null);
  useEffect(() => {
    let cancelled = false;
    fetch('data/card_manifest.json')
      .then(res => res.json())
      .then(data => {
        if (!cancelled) setCardManifest(data);
      })
      .catch(() => {
        if (!cancelled) setCardManifest(null);
      });
    return () => { cancelled = true; };
  }, []);
  return cardManifest;
}

// Load backgrounds manifest (generated by scripts/generate_background_manifest.py)
function useBackgroundsManifest() {
  const [backgroundsManifest, setBackgroundsManifest] = useState(null);
  useEffect(() => {
    let cancelled = false;
    fetch('data/backgrounds_manifest.json')
      .then(res => res.json())
      .then(data => { if (!cancelled) setBackgroundsManifest(data); })
      .catch(() => { if (!cancelled) setBackgroundsManifest(null); });
    return () => { cancelled = true; };
  }, []);
  return backgroundsManifest;
}

// Load silhouette metadata once at app level to avoid repeated network calls
function useSilhouetteMeta() {
  const [silhouetteMeta, setSilhouetteMeta] = useState(null);
  useEffect(() => {
    let cancelled = false;
    fetch('data/silhouette_meta.json')
      .then(res => res.json())
      .then(data => {
        if (!cancelled) setSilhouetteMeta(data);
      })
      .catch(() => {
        if (!cancelled) setSilhouetteMeta(null);
      });
    return () => { cancelled = true; };
  }, []);
  return silhouetteMeta;
}

// Load zoom metadata once at app level (similar to silhouette_meta.json)
function useZoomMeta() {
  const [zoomMeta, setZoomMeta] = useState(null);
  useEffect(() => {
    let cancelled = false;
    fetch('data/zoom_meta.json')
      .then(res => res.json())
      .then(data => {
        if (!cancelled) setZoomMeta(data);
      })
      .catch(() => {
        if (!cancelled) setZoomMeta(null);
      });
    return () => { cancelled = true; };
  }, []);
  return zoomMeta;
}

// Load eyes manifest (list of available eye image filenames)
function useEyesManifest() {
  const [eyesManifest, setEyesManifest] = useState(null);
  useEffect(() => {
    let cancelled = false;
    fetch('data/eyes_manifest.json')
      .then(res => res.json())
      .then(data => {
        if (!cancelled) setEyesManifest(data);
      })
      .catch(() => {
        if (!cancelled) setEyesManifest(null);
      });
    return () => { cancelled = true; };
  }, []);
  return eyesManifest;
}

// Load body parts manifest (object keyed by pokemon ID listing part image filenames)
function useBodyPartsManifest() {
  const [bodyPartsManifest, setBodyPartsManifest] = useState(null);
  useEffect(() => {
    let cancelled = false;
    fetch('data/body_parts_manifest.json')
      .then(res => res.json())
      .then(data => {
        if (!cancelled) setBodyPartsManifest(data);
      })
      .catch(() => {
        if (!cancelled) setBodyPartsManifest(null);
      });
    return () => { cancelled = true; };
  }, []);
  return bodyPartsManifest;
}

function useTitleImg() {
  // Just return the public path
  return 'data/title.png';
}
import './App.css';


import ClassicPage from './pages/ClassicPage';
import PokedexPage from './pages/PokedexPage';
import SilhouettePage from './pages/SilhouettePage';
import ZoomPage from './pages/ZoomPage';
import ColoursPage from './pages/ColoursPage';
import CardPage from './pages/CardPage';
import LocationsPage from './pages/LocationsPage';
import EyesPage from './pages/EyesPage';
import { getCardTypeByDay } from './utils/cardType';
import Header from './components/Header';
import ResultsPage from './pages/ResultsPage';
import PatchNotesPage from './pages/PatchNotesPage';
import AboutPage from './pages/AboutPage';
import PrivacyPolicyPage from './pages/PrivacyPolicyPage';
import { getDailyOverride, getDailyTheme } from './config/dailyOverrides';


// Simple deterministic PRNG using a seed
function mulberry32(a) {
  return function() {
    var t = a += 0x6D2B79F5;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  }
}

function getSeedFromDate(date) {
  // YYYYMMDD as integer, using the app-wide UTC reset hour
  // If current UTC hour is on/after the reset hour, use the next UTC day
  let effective = date;
  if (date.getUTCHours() >= RESET_HOUR_UTC) {
    effective = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate() + 1, 0, 0, 0));
  }
  return parseInt(effective.toISOString().slice(0,10).replace(/-/g, ''), 10);
}
const PAGES = [
  { key: 'classic', label: 'Classic' },
  { key: 'card', label: 'Card' },
  { key: 'pokedex', label: 'Pokedex' },
  { key: 'details', label: 'Details' },
  { key: 'colours', label: 'Colours' },
  { key: 'map', label: 'Locations' },
  { key: 'results', label: 'Results' },
];

// Determine which detail mode (silhouette or zoom) based on UTC day of week
// Monday=1, Wednesday=3, Friday=5, Saturday=6 → Silhouette
// Tuesday=2, Thursday=4, Sunday=0 → Zoom
function getDetailsModeForDate(date) {
  let effective = date;
  if (date.getUTCHours() >= RESET_HOUR_UTC) {
    effective = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate() + 1, 0, 0, 0));
  }
  const utcDay = effective.getUTCDay(); // 0=Sunday, 1=Monday, ..., 6=Saturday
  // Silhouette days: 1 (Mon), 4 (Thu)
  if (utcDay === 1 || utcDay === 4) {
    return 'silhouette';
  }
  // Zoom days: 2 (Tue), 5 (Friday), 0 (Sun)
  if (utcDay === 2 || utcDay === 5 || utcDay === 0) {
    return 'zoom';
  }
  // Features days: 3 (Wed), 6 (Sat)
  if (utcDay === 3 || utcDay === 6) {
    return 'features';
  }
}

function App() {
  const pokemonData = usePokemonData();
  const cardManifest = useCardManifest();
  const backgroundsManifest = useBackgroundsManifest();
  const silhouetteMeta = useSilhouetteMeta();
  const zoomMeta = useZoomMeta();
  const eyesManifest = useEyesManifest();
  const bodyPartsManifest = useBodyPartsManifest();
  const titleImg = useTitleImg();
  
  // Clean up old confetti localStorage entries on mount
  useEffect(() => {
    try {
      const today = new Date();
      const todaySeed = getSeedFromDate(today);
      
      // Calculate yesterday's seed for comparison
      const yesterday = new Date(today);
      yesterday.setDate(yesterday.getDate() - 1);
      const yesterdaySeed = getSeedFromDate(yesterday);
      
      const keysToRemove = [];
      
      // Scan all localStorage keys for old daily entries (confetti, emoji, phrase)
      const dailyPrefixes = ['pokedle_confetti_', 'pokedle_emoji_', 'pokedle_phrase_'];
      
      for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        if (key && dailyPrefixes.some(prefix => key.startsWith(prefix))) {
          // Extract the seed from the key (format: pokedle_<type>_<mode>_<seed>)
          // The seed might have offsets added, but the base date seed is in the same range
          const parts = key.split('_');
          const seedStr = parts[parts.length - 1];
          const seed = parseInt(seedStr, 10);
          
          // Remove if the base date portion is clearly from a previous day
          // Seeds are YYYYMMDD format, so check if it's before yesterday
          if (!isNaN(seed)) {
            const baseDatePortion = Math.floor(seed / 10000) * 10000 + (seed % 10000);
            // If base date is older than yesterday, remove it
            if (baseDatePortion < yesterdaySeed) {
              keysToRemove.push(key);
            }
          }
        }
      }
      
      // Remove old entries
      keysToRemove.forEach(key => localStorage.removeItem(key));
      
      if (keysToRemove.length > 0) {
        // console.log(`Cleaned up ${keysToRemove.length} old daily entries`);
      }
    } catch (e) {
      // Ignore localStorage errors
    }
  }, []);
  
  // Preload navigation icons (including the Results icon) so they appear immediately when header renders
  useEffect(() => {
    const imgs = [];
    try {
      const iconPaths = PAGES.map(p => `icons/${p.key}.png`).concat(['icons/results.png']);
      iconPaths.forEach(path => {
        const img = new Image();
        img.src = path;
        imgs.push(img);
      });
    } catch (e) {
      // ignore
    }
    return () => {
      // help GC
      imgs.length = 0;
    };
  }, []);
  const [page, setPage] = useState('classic');
  const [compactNav, setCompactNav] = useState(() => (typeof window !== 'undefined') ? window.innerWidth <= 1080 : false);
  const [menuOpen, setMenuOpen] = useState(false);
  // Mobile swipe navigation: track small viewport and attach touch handlers
  const mainAppRef = useRef(null);
  const [isMobileView, setIsMobileView] = useState(() => (typeof window !== 'undefined' && window.matchMedia) ? window.matchMedia('(max-width:700px)').matches : false);
  useEffect(() => {
    if (typeof window === 'undefined' || !window.matchMedia) return;
    const mq = window.matchMedia('(max-width:700px)');
    const onChange = e => setIsMobileView(e.matches);
    try {
      mq.addEventListener ? mq.addEventListener('change', onChange) : mq.addListener(onChange);
    } catch (e) {
      mq.addListener(onChange);
    }
    return () => {
      try {
        mq.removeEventListener ? mq.removeEventListener('change', onChange) : mq.removeListener(onChange);
      } catch (e) {
        mq.removeListener(onChange);
      }
    };
  }, []);

  useEffect(() => {
    if (!isMobileView) return;
    let startX = 0;
    let startY = 0;
    let startTime = 0;
    let ignore = false;
    const THRESHOLD = 50; // px
    const MAX_TIME = 1000; // ms

    function onTouchStart(e) {
      if (!e.touches || e.touches.length === 0) return;
      const t = e.touches[0];
      // Only start tracking if the touch began inside the main-app container
      if (mainAppRef && mainAppRef.current && !mainAppRef.current.contains(t.target)) {
        ignore = true;
        return;
      }
      ignore = false;
      startX = t.clientX;
      startY = t.clientY;
      startTime = Date.now();
    }

    function onTouchEnd(e) {
      if (ignore) return;
      const t = (e.changedTouches && e.changedTouches[0]) || null;
      if (!t) return;
      const dx = t.clientX - startX;
      const dy = t.clientY - startY;
      const dt = Date.now() - startTime;
      if (dt > MAX_TIME) return;
      if (Math.abs(dx) < THRESHOLD) return;
      if (Math.abs(dx) < Math.abs(dy)) return; // primarily vertical gesture

      const idx = PAGES.findIndex(p => p.key === page);
      if (idx === -1) return;
      // Move one page left/right but do NOT wrap around — clamp at ends
      let newIdx = idx + (dx < 0 ? 1 : -1);
      newIdx = Math.max(0, Math.min(PAGES.length - 1, newIdx));
      if (newIdx !== idx) {
        // start animated transition between pages on mobile
        const direction = dx < 0 ? 'left' : 'right';
        startPageTransition(PAGES[newIdx].key, direction);
      }
    }

    document.addEventListener('touchstart', onTouchStart, { passive: true });
    document.addEventListener('touchend', onTouchEnd, { passive: true });
    return () => {
      document.removeEventListener('touchstart', onTouchStart);
      document.removeEventListener('touchend', onTouchEnd);
    };
  }, [isMobileView, page]);

  // Compact header mode: compute at app level and pass to Header
  useEffect(() => {
    function updateCompact() {
      try {
        const isNarrow = (typeof window !== 'undefined') && window.innerWidth <= 1080;
        setCompactNav(isNarrow);
      } catch (e) {}
    }
    updateCompact();
    window.addEventListener('resize', updateCompact);
    return () => window.removeEventListener('resize', updateCompact);
  }, []);
  // Store guesses per page with localStorage persistence
  const [guessesByPage, setGuessesByPage] = useState(() => {
    // Load from localStorage on mount
    try {
      const stored = localStorage.getItem('pokedle_guesses');
      if (stored) {
        const data = JSON.parse(stored);
        // Check if the stored data is for today
        const storedDate = data.date;
        const todaySeed = getSeedFromDate(new Date());
        if (storedDate === todaySeed) {
          return data.guesses || {};
        }
      }
    } catch (e) {
      // console.error('Failed to load guesses from localStorage:', e);
    }
    // Return default empty guesses if nothing stored or data is old
    return {
      classic: [],
      pokedex: [],
      stats: [],
      ability: [],
      moves: [],
      category: [],
      details: [],
      colours: [],
      locations: [],
      card: []
    };
  });

  // Persist guesses to localStorage whenever they change
  useEffect(() => {
    try {
      const todaySeed = getSeedFromDate(new Date());
      const data = {
        date: todaySeed,
        guesses: guessesByPage
      };
      localStorage.setItem('pokedle_guesses', JSON.stringify(data));
      // Also save under a dated key so yesterday-mode can retrieve them after the day rolls over
      localStorage.setItem(`pokedle_guesses_${todaySeed}`, JSON.stringify(data));
    } catch (e) {
      // console.error('Failed to save guesses to localStorage:', e);
    }
  }, [guessesByPage]);

  // Debug state for testing different days
  const [debugDayOffset, setDebugDayOffset] = useState(0);
  const [debugPanelOpen, setDebugPanelOpen] = useState(false);

  // Yesterday mode
  const [yesterdayMode, setYesterdayMode] = useState(false);

  // yesterdayDate and yesterdaySeed must be declared here so the persist effect below can use them.
  // They depend on debugDayOffset (via today logic), but today is declared after this block.
  // We compute them independently from new Date() + debugDayOffset to avoid the TDZ issue.
  const yesterdayDate = useMemo(() => {
    const base = new Date();
    if (debugDayOffset !== 0) base.setDate(base.getDate() + debugDayOffset);
    base.setDate(base.getDate() - 1);
    return base;
  }, [debugDayOffset]);

  const yesterdaySeed = useMemo(() => getSeedFromDate(yesterdayDate), [yesterdayDate]);

  const [yesterdayGuessesByPage, setYesterdayGuessesByPage] = useState(() => {
    try {
      const now = new Date();
      const yDate = new Date(now);
      yDate.setDate(yDate.getDate() - 1);
      const ySeed = getSeedFromDate(yDate);
      // Try dated key first (populated after playing today, or carried over)
      const datedStored = localStorage.getItem(`pokedle_guesses_${ySeed}`);
      if (datedStored) {
        const data = JSON.parse(datedStored);
        if (data.date === ySeed) return data.guesses || {};
      }
      // Fallback: main key still has yesterday's data (user hasn't played today yet)
      const stored = localStorage.getItem('pokedle_guesses');
      if (stored) {
        const data = JSON.parse(stored);
        if (data.date === ySeed) return data.guesses || {};
      }
    } catch (e) {}
    return { classic: [], pokedex: [], details: [], colours: [], map: [], card: [] };
  });

  // Persist yesterday guesses under their dated key
  useEffect(() => {
    try {
      localStorage.setItem(`pokedle_guesses_${yesterdaySeed}`, JSON.stringify({ date: yesterdaySeed, guesses: yesterdayGuessesByPage }));
    } catch (e) {}
  }, [yesterdayGuessesByPage, yesterdaySeed]);
  const [highlightedIdx, setHighlightedIdx] = useState(-1);
  const [dropdownOpen, setDropdownOpen] = useState(false);
  const inputRef = useRef(null);
  const dropdownRef = useRef(null);
  // Page transition state for animated mobile swipes
  const [pageTransition, setPageTransition] = useState(null);

  function startPageTransition(toKey, direction) {
    if (!toKey || toKey === page) return;
    if (pageTransition) return; // already animating
    // direction: 'left' means go to next (from left->right), 'right' means previous
    setPageTransition({ from: page, to: toKey, direction, animate: false });
    // Trigger animation on next frame
    requestAnimationFrame(() => {
      setPageTransition(prev => prev ? { ...prev, animate: true } : prev);
    });
  }

  // Get today's date as seed, use page key for deterministic daily selection per page
  // Apply debug day offset if set
  const today = useMemo(() => {
    const base = new Date();
    if (debugDayOffset !== 0) {
      base.setDate(base.getDate() + debugDayOffset);
    }
    return base;
  }, [debugDayOffset]);

  // yesterdayDate and yesterdaySeed are declared earlier (before yesterdayGuessesByPage) to avoid TDZ issues.
  // isShinyDay is derived from the actual card selected for today (computed after dailyByPage)
  const todayTheme = getDailyTheme(getSeedFromDate(today));
  const seed = getSeedFromDate(today) + page.length * 1000 + page.charCodeAt(0);
  const rng = useMemo(() => mulberry32(seed), [seed]);
  // Pick daily pokemon for the current page
  const dailyIndex = useMemo(() => pokemonData ? Math.floor(rng() * pokemonData.length) : 0, [rng, pokemonData]);
  const dailyPokemon = pokemonData ? pokemonData[dailyIndex] : null;

  // Helper function to get Pokemon IDs selected in the previous N days for a specific mode
  // Returns a Set of Pokemon IDs that should be excluded
  const getRecentPokemonIds = useCallback((currentDate, modeKey, lookbackDays = 28) => {
    if (!pokemonData) return new Set();
    
    const cache = new Map();
    const excludedIds = new Set();
    
    // Get details mode for current date
    const currentDetailsMode = getDetailsModeForDate(currentDate);
    const SEED_OFFSETS = {
      classic: { offset: 6 * 452, letter: 'c' },
      card: { offset: 9999, letter: null },
      pokedex: { offset: 7 * 3355, letter: 'p' },
      details: currentDetailsMode === 'silhouette' ? { offset: 7 * 1000, letter: 's' } : (currentDetailsMode === 'zoom' ? { offset: 8 * 1000, letter: 'z' } : { offset: 14 * 1000, letter: 'e' }),
      colours: { offset: 9 * 5657, letter: 'c' },
      map: { offset: 13 * 5575, letter: 'g' },
    };
    
    const meta = SEED_OFFSETS[modeKey] || { offset: modeKey.length * 1000, letter: modeKey.charAt(0) };
    
    // Debug logging for Locations mode - show what we're building
    if (modeKey === 'map') {
      const currentDateStr = currentDate.toISOString().split('T')[0];
      // console.log(`[Locations Lookback START] Building exclusions for ${currentDateStr}, looking back ${lookbackDays} days`);
    }
    
    // Build selections iteratively from oldest to newest to avoid recursion
    // We need to look back 2x the lookback window to ensure we have enough history
    // for each past date to have its own 28-day exclusion list
    const totalLookback = lookbackDays * 2;
    for (let daysBack = totalLookback; daysBack >= 1; daysBack--) {
      const pastDate = new Date(currentDate);
      pastDate.setDate(pastDate.getDate() - daysBack);
      const pastSeed = getSeedFromDate(pastDate);
      const pastDetailsMode = getDetailsModeForDate(pastDate);
      
      // Debug logging for Locations mode - show each iteration
      if (modeKey === 'map' && daysBack <= lookbackDays) {
        const pastDateStr = pastDate.toISOString().split('T')[0];
        // console.log(`[Locations Lookback] Processing day -${daysBack}: ${pastDateStr}`);
      }
      
      // Check for override first
      const override = getDailyOverride(pastSeed, modeKey);
      let selectedId;
      
      if (override && typeof override === 'number') {
        selectedId = override;
      } else if (override && typeof override === 'object' && override.pokemonId) {
        selectedId = override.pokemonId;
      } else {
        // Build exclusion set for this past date from dates we've already processed (older dates)
        // Each date should exclude the 28 days before IT, not just the dates within our window
        const pastExcludedIds = new Set();
        for (let olderDaysBack = daysBack + 1; olderDaysBack <= daysBack + lookbackDays; olderDaysBack++) {
          const olderDate = new Date(currentDate);
          olderDate.setDate(olderDate.getDate() - olderDaysBack);
          const olderKey = `${olderDate.getTime()}-${modeKey}`;
          const olderId = cache.get(olderKey);
          if (olderId !== undefined) {
            pastExcludedIds.add(olderId);
          }
        }
        
        // Debug logging for Locations mode
        if (modeKey === 'map' && daysBack <= lookbackDays) {
          const pastDateStr = pastDate.toISOString().split('T')[0];
          // console.log(`[Locations Lookback]   Building exclusions for ${pastDateStr}: ${pastExcludedIds.size} Pokemon excluded`);
        }
        
        // Calculate seed for this past date
        let seedFor;
        if (modeKey === 'details') {
          const pastMeta = pastDetailsMode === 'silhouette' 
            ? { offset: 7 * 1000, letter: 's' }
            : (pastDetailsMode === 'zoom' ? { offset: 8 * 1000, letter: 'z' } : { offset: 14 * 1000, letter: 'e' });
          seedFor = pastSeed + pastMeta.offset + (pastMeta.letter ? pastMeta.letter.charCodeAt(0) : 0);
        } else {
          seedFor = pastSeed + meta.offset + (meta.letter ? meta.letter.charCodeAt(0) : 0);
        }
        
        // Replay selection logic for this past date
        if (modeKey === 'details' && pastDetailsMode === 'eyes' && bodyPartsManifest) {
          // Features mode: manifest-based selection
          const rngFor = mulberry32(seedFor);
          let found = false;
          let attempts = 0;
          while (attempts < 200 && !found) {
            const idx = Math.floor(rngFor() * pokemonData.length);
            const candidate = pokemonData[idx];
            if (bodyPartsManifest?.trimmed?.[String(candidate.id)]?.length > 0 && !pastExcludedIds.has(candidate.id)) {
              selectedId = candidate.id;
              found = true;
            }
            attempts++;
          }
        } else {
          // Regular selection with anti-repeat
          const rngFor = mulberry32(seedFor);
          let found = false;
          let attempts = 0;
          while (attempts < pokemonData.length && !found) {
            const idx = Math.floor(rngFor() * pokemonData.length);
            const candidate = pokemonData[idx];
            if (!pastExcludedIds.has(candidate.id)) {
              selectedId = candidate.id;
              found = true;
            }
            attempts++;
          }
        }
      }
      
      // Store in cache
      if (selectedId !== undefined) {
        const cacheKey = `${pastDate.getTime()}-${modeKey}`;
        cache.set(cacheKey, selectedId);
        
        // Only add to exclusion list if within the lookback window (not the extended window)
        if (daysBack <= lookbackDays) {
          excludedIds.add(selectedId);
        }
        
        // Debug logging for Locations mode
        if (modeKey === 'map' && daysBack <= lookbackDays) {
          const dateStr = pastDate.toISOString().split('T')[0];
          const pokemon = pokemonData.find(p => p.id === selectedId);
          // console.log(`[Locations Lookback]   -> Selected: ${pokemon?.name || 'Unknown'} (ID: ${selectedId})`);
        }
      }
    }
    
    // Debug logging for Locations mode
    if (modeKey === 'map') {
      // console.log(`[Locations Lookback END] Total excluded: ${excludedIds.size} Pokemon`);
    }
    
    return excludedIds;
  }, [pokemonData, bodyPartsManifest]);

  // Helper function to select the Pokemon for a specific date and mode
  // This replicates the exact selection logic including anti-repeat filtering
  const selectPokemonForDate = useCallback((targetDate, modeKey) => {
    if (!pokemonData) return null;
    
    const targetSeed = getSeedFromDate(targetDate);
    const targetDetailsMode = getDetailsModeForDate(targetDate);
    
    // Check for override first
    const override = getDailyOverride(targetSeed, modeKey);
    if (override && typeof override === 'number') {
      const chosen = pokemonData.find(p => p.id === override);
      return chosen || null;
    } else if (override && typeof override === 'object' && override.pokemonId) {
      const chosen = pokemonData.find(p => p.id === override.pokemonId);
      return chosen || null;
    }
    
    // Get exclusion list for this date
    const excludedIds = getRecentPokemonIds(targetDate, modeKey);
    
    // Debug logging for Locations mode
    if (modeKey === 'map') {
      const dateStr = targetDate.toISOString().split('T')[0];
      // console.log(`[Locations SELECT] Selecting for ${dateStr}, excluded: ${excludedIds.size} Pokemon, IDs: [${Array.from(excludedIds).sort((a, b) => a - b).join(', ')}]`);
    }
    
    // Determine seed based on mode - calculate SEED_OFFSETS locally
    const detailsModeSeedOffsets = targetDetailsMode === 'silhouette' 
      ? { offset: 7 * 1000, letter: 's' }
      : (targetDetailsMode === 'zoom' ? { offset: 8 * 1000, letter: 'z' } : { offset: 14 * 1000, letter: 'e' });
    
    const SEED_OFFSETS = {
      classic: { offset: 6 * 452, letter: 'c' },
      card: { offset: 9999, letter: null },
      pokedex: { offset: 7 * 3355, letter: 'p' },
      details: detailsModeSeedOffsets,
      colours: { offset: 9 * 5657, letter: 'c' },
      map: { offset: 13 * 5575, letter: 'g' },
    };
    
    const meta = SEED_OFFSETS[modeKey] || { offset: modeKey.length * 1000, letter: modeKey.charAt(0) };
    let seedFor;
    
    if (modeKey === 'details') {
      const detailMeta = targetDetailsMode === 'silhouette' 
        ? { offset: 7 * 1000, letter: 's' }
        : (targetDetailsMode === 'zoom' ? { offset: 8 * 1000, letter: 'z' } : { offset: 14 * 1000, letter: 'e' });
      seedFor = targetSeed + detailMeta.offset + (detailMeta.letter ? detailMeta.letter.charCodeAt(0) : 0);
    } else {
      seedFor = targetSeed + meta.offset + (meta.letter ? meta.letter.charCodeAt(0) : 0);
    }
    
    // Select Pokemon based on mode
    let selected = null;
    
    if (modeKey === 'details' && targetDetailsMode === 'eyes' && bodyPartsManifest) {
      // Features mode: manifest-based selection
      const rngFor = mulberry32(seedFor);
      let attempts = 0;
      while (attempts < 200) {
        const idx = Math.floor(rngFor() * pokemonData.length);
        const candidate = pokemonData[idx];
        if (bodyPartsManifest?.trimmed?.[String(candidate.id)]?.length > 0 && !excludedIds.has(candidate.id)) {
          selected = candidate;
          break;
        }
        attempts++;
      }
      
      // Fallback
      if (!selected) {
        const fallbackRng = mulberry32(seedFor);
        let fallbackAttempts = 0;
        while (fallbackAttempts < 200) {
          const idx = Math.floor(fallbackRng() * pokemonData.length);
          const candidate = pokemonData[idx];
          if (bodyPartsManifest?.trimmed?.[String(candidate.id)]?.length > 0) {
            selected = candidate;
            break;
          }
          fallbackAttempts++;
        }
      }
    } else {
      // Regular selection with anti-repeat
      const rngFor = mulberry32(seedFor);
      let attempts = 0;
      
      // Debug logging for Locations mode
      if (modeKey === 'map') {
        // console.log(`[Locations SELECT] Starting selection loop, excludedIds size: ${excludedIds.size}`);
      }
      
      while (attempts < pokemonData.length) {
        const idx = Math.floor(rngFor() * pokemonData.length);
        const candidate = pokemonData[idx];
        
        // Debug logging for Locations mode
        if (modeKey === 'map' && attempts < 10) {
          const isExcluded = excludedIds.has(candidate.id);
          // console.log(`[Locations SELECT]   Attempt ${attempts}: idx=${idx}, ${candidate.name} (ID: ${candidate.id}), excluded=${isExcluded}`);
        }
        
        if (!excludedIds.has(candidate.id)) {
          selected = candidate;
          
          // Debug logging for Locations mode
          if (modeKey === 'map') {
            // console.log(`[Locations SELECT]   ✓ Found non-excluded Pokemon after ${attempts} attempts: ${candidate.name} (ID: ${candidate.id})`);
          }
          
          break;
        }
        attempts++;
      }
      
      // Fallback
      if (!selected) {
        // Debug logging for Locations mode
        if (modeKey === 'map') {
          // console.log(`[Locations SELECT]   ⚠ FALLBACK: Could not find non-excluded Pokemon, selecting random one`);
        }
        
        const fallbackRng = mulberry32(seedFor);
        const idx = Math.floor(fallbackRng() * pokemonData.length);
        selected = pokemonData[idx];
        
        // Debug logging for Locations mode
        if (modeKey === 'map') {
          // console.log(`[Locations SELECT]   ⚠ FALLBACK selected: ${selected.name} (ID: ${selected.id})`);
        }
      }
    }
    
    // Debug logging for Locations mode
    if (modeKey === 'map' && selected) {
      const dateStr = targetDate.toISOString().split('T')[0];
      // console.log(`[Locations SELECT]   -> FINAL: ${selected.name} (ID: ${selected.id})\n`);
    }
    
    return selected;
  }, [pokemonData, bodyPartsManifest, getRecentPokemonIds]);

  // Compute the daily card selection for a given date (extracted so it can be reused for yesterday mode)
  const getCardAnswerForDate = useCallback((targetDate) => {
    if (!cardManifest || !pokemonData) return null;
    const targetSeed = getSeedFromDate(targetDate);
    const excludedIds = getRecentPokemonIds(targetDate, 'card');

    // Check for override first
    const override = getDailyOverride(targetSeed, 'card');
    if (override && typeof override === 'object' && override.pokemonId) {
      const chosen = pokemonData.find(p => p.id === override.pokemonId);
      if (chosen && cardManifest) {
        let cardType = override.cardType;
        let cardFile = override.cardFile;
        if (cardFile && !cardType) {
          for (const type of ['normal', 'full_art', 'shiny', 'special']) {
            const manifestList = cardManifest[type]?.[chosen.id];
            if (manifestList && manifestList.includes(cardFile)) { cardType = type; break; }
          }
        }
        if (!cardType) cardType = 'normal';
        const manifestList = cardManifest[cardType]?.[chosen.id];
        if (manifestList && manifestList.length > 0) {
          if (!cardFile || !manifestList.includes(cardFile)) cardFile = manifestList[0];
          const folder = `https://raw.githubusercontent.com/Pythagean/pokedle_assets/main/cards/${cardType}`;
          const cardObj = (cardType === 'normal' || cardType === 'shiny')
            ? { cropped: `${folder}/cropped/${cardFile}`, resized: `${folder}/resized/${cardFile}`, cardFile, folder, cardType }
            : { cropped: `${folder}/${cardFile}`, resized: `${folder}/${cardFile}`, cardFile, folder, cardType };
          return { pokemon: chosen, card: cardObj };
        }
      }
    }

    const baseSeed = targetSeed + 9999;
    let localRng = mulberry32(baseSeed);
    const BASE_URL = 'https://raw.githubusercontent.com/Pythagean/pokedle_assets/main/cards';

    // Use targetDate for day-of-week to correctly determine weekend vs weekday card type
    let dayForCard = new Date(Date.UTC(targetDate.getUTCFullYear(), targetDate.getUTCMonth(), targetDate.getUTCDate(), 0, 0, 0));
    if (targetDate.getUTCHours() >= RESET_HOUR_UTC) {
      dayForCard = new Date(Date.UTC(targetDate.getUTCFullYear(), targetDate.getUTCMonth(), targetDate.getUTCDate() + 1, 0, 0, 0));
    }
    const isWeekend = dayForCard.getUTCDay() === 0 || dayForCard.getUTCDay() === 6;

    function buildCardForPokemon(chosen) {
      if (isWeekend) {
        const manifestList = cardManifest['special']?.[chosen.id];
        if (!manifestList || manifestList.length === 0) return null;
        const cardFile = manifestList[Math.floor(localRng() * manifestList.length)];
        const folder = `${BASE_URL}/special`;
        return { cropped: `${folder}/${cardFile}`, resized: `${folder}/${cardFile}`, cardFile, folder, cardType: 'special' };
      }
      const normalList = cardManifest['normal']?.[chosen.id];
      if (!normalList || normalList.length === 0) return null;
      const typeRng = mulberry32(baseSeed + chosen.id * 7777);
      const fullArtRoll = typeRng();
      const shinyRoll = typeRng();
      const hasFullArt = cardManifest['full_art']?.[chosen.id]?.length > 0;
      const shinyData = cardManifest['shiny']?.[chosen.id];
      const shinyRegularFiles = shinyData?.regular || [];
      const shinyFullFiles = shinyData?.full || [];
      const hasShinySomething = shinyRegularFiles.length > 0 || shinyFullFiles.length > 0;
      if (fullArtRoll < 0.05 && hasFullArt) {
        const fullArtList = cardManifest['full_art'][chosen.id];
        const cardFile = fullArtList[Math.floor(localRng() * fullArtList.length)];
        const folder = `${BASE_URL}/full_art`;
        return { cropped: `${folder}/${cardFile}`, resized: `${folder}/${cardFile}`, cardFile, folder, cardType: 'full_art' };
      } else if (shinyRoll < 0.05 && hasShinySomething) {
        const allShinyFiles = [
          ...shinyRegularFiles.map(f => ({ file: f, variant: 'regular' })),
          ...shinyFullFiles.map(f => ({ file: f, variant: 'full' }))
        ];
        const entry = allShinyFiles[Math.floor(localRng() * allShinyFiles.length)];
        const baseShinyFolder = `${BASE_URL}/shiny`;
        return entry.variant === 'regular'
          ? { cropped: `${baseShinyFolder}/regular/cropped/${entry.file}`, resized: `${baseShinyFolder}/regular/${entry.file}`, cardFile: entry.file, folder: `${baseShinyFolder}/regular`, cardType: 'shiny', shinyVariant: 'regular' }
          : { cropped: `${baseShinyFolder}/full/${entry.file}`, resized: `${baseShinyFolder}/full/${entry.file}`, cardFile: entry.file, folder: `${baseShinyFolder}/full`, cardType: 'shiny', shinyVariant: 'full' };
      } else {
        const cardFile = normalList[Math.floor(localRng() * normalList.length)];
        const folder = `${BASE_URL}/normal`;
        return { cropped: `${folder}/cropped/${cardFile}`, resized: `${folder}/resized/${cardFile}`, cardFile, folder, cardType: 'normal' };
      }
    }

    let attempts = 0;
    while (attempts < 200) {
      const idx = Math.floor(localRng() * pokemonData.length);
      const chosen = pokemonData[idx];
      if (!excludedIds.has(chosen.id)) {
        const cardObj = buildCardForPokemon(chosen);
        if (cardObj) return { pokemon: chosen, card: cardObj };
      }
      attempts++;
    }
    // Fallback: allow repeats
    localRng = mulberry32(baseSeed);
    attempts = 0;
    while (attempts < 200) {
      const idx = Math.floor(localRng() * pokemonData.length);
      const chosen = pokemonData[idx];
      const cardObj = buildCardForPokemon(chosen);
      if (cardObj) return { pokemon: chosen, card: cardObj };
      attempts++;
    }
    return null;
  }, [cardManifest, pokemonData, getRecentPokemonIds]);

  // Compute per-page daily pokemon and solved status (run this hook unconditionally)
  const perPageResults = useMemo(() => {
    if (!pokemonData) return [];

    const todaySeed = getSeedFromDate(today);
    const detailsMode = getDetailsModeForDate(today);
    const SEED_OFFSETS = {
      classic: { offset: 6 * 452, letter: 'c' },
      card: { offset: 9999, letter: null },
      pokedex: { offset: 7 * 3355, letter: 'p' },
      details: detailsMode === 'silhouette' ? { offset: 7 * 1000, letter: 's' } : (detailsMode === 'zoom' ? { offset: 8 * 1000, letter: 'z' } : { offset: 14 * 1000, letter: 'e' }),
      colours: { offset: 9 * 5657, letter: 'c' },
      map: { offset: 13 * 5575, letter: 'g' },
    };

    function getEyesAnswer() {
      // Select a pokemon that has body part images in the manifest
      if (!bodyPartsManifest) return null;
      
      // Get recently used Pokemon IDs to exclude
      const excludedIds = getRecentPokemonIds(today, 'details');
      
      // Check for override first
      const override = getDailyOverride(todaySeed, 'details');
      if (override && typeof override === 'number') {
        const chosen = pokemonData.find(p => p.id === override);
        if (chosen && bodyPartsManifest?.trimmed?.[String(chosen.id)]?.length > 0) {
          return chosen;
        }
      }

      // Randomly select a pokemon that has body part images in the manifest and is not recently used
      const seedFor = getSeedFromDate(today) + 14 * 1000 + 'e'.charCodeAt(0);
      let localRng = mulberry32(seedFor);
      let attempts = 0;
      while (attempts < 200) {
        const idx = Math.floor(localRng() * pokemonData.length);
        const chosen = pokemonData[idx];
        if (bodyPartsManifest?.trimmed?.[String(chosen.id)]?.length > 0 && !excludedIds.has(chosen.id)) {
          return chosen;
        }
        attempts++;
      }
      
      // Fallback: if we can't find a non-repeating Pokemon, just pick any valid one
      localRng = mulberry32(seedFor);
      attempts = 0;
      while (attempts < 200) {
        const idx = Math.floor(localRng() * pokemonData.length);
        const chosen = pokemonData[idx];
        if (bodyPartsManifest?.trimmed?.[String(chosen.id)]?.length > 0) {
          return chosen;
        }
        attempts++;
      }
      
      return null;
    }

    function getCardAnswer() {
      return getCardAnswerForDate(today);
    }

    return PAGES.filter(p => p.key !== 'results').map(p => {
      const meta = SEED_OFFSETS[p.key] || { offset: p.key.length * 1000, letter: p.key.charAt(0) };
      let seedFor;
      if (p.key === 'card') {
        // Card page uses a special base seed and additional manifest-based filtering
        const cardAnswerObj = getCardAnswer(); // { pokemon, card }
        const pageGuesses = guessesByPage[p.key] || [];
        const solved = cardAnswerObj && cardAnswerObj.pokemon && pageGuesses.some(g => g.name === cardAnswerObj.pokemon.name);
        return { key: p.key, label: p.label, daily: cardAnswerObj, solved, guessCount: solved ? pageGuesses.length : null };
      } else if (p.key === 'details' && detailsMode === 'eyes') {
        // Eyes mode requires manifest filtering like card page
        const eyesAnswer = getEyesAnswer();
        console.log('[Eyes] Selected daily eyes Pokemon:', eyesAnswer?.name, eyesAnswer?.id);
        const pageGuesses = guessesByPage[p.key] || [];
        const solved = eyesAnswer && pageGuesses.some(g => g.name === eyesAnswer.name);
        return { key: p.key, label: p.label, daily: eyesAnswer, solved, guessCount: solved ? pageGuesses.length : null };
      } else {
        seedFor = getSeedFromDate(today) + meta.offset + (meta.letter ? meta.letter.charCodeAt(0) : 0);
      }
      
      // Use the helper function to ensure consistency with debug grid
      const daily = selectPokemonForDate(today, p.key);
      
      const pageGuesses = guessesByPage[p.key] || [];
      const solved = daily && pageGuesses.some(g => g.name === (daily.name));
      return { key: p.key, label: p.label, daily, solved, guessCount: solved ? pageGuesses.length : null };
    });
  }, [pokemonData, guessesByPage, today, cardManifest, bodyPartsManifest, getCardAnswerForDate, selectPokemonForDate]);

  // Map of daily pokemon objects by page key for easy access and prop passing
  const dailyByPage = useMemo(() => {
    const map = {};
    perPageResults.forEach(r => { map[r.key] = r.daily || null; });
    return map;
  }, [perPageResults]);

  const yesterdayPerPageResults = useMemo(() => {
    if (!pokemonData) return [];
    return PAGES.filter(p => p.key !== 'results').map(p => {
      let daily;
      if (p.key === 'card') {
        daily = getCardAnswerForDate(yesterdayDate);
      } else {
        daily = selectPokemonForDate(yesterdayDate, p.key);
      }
      const pokemonForComparison = p.key === 'card' ? daily?.pokemon : daily;
      const pageGuesses = yesterdayGuessesByPage[p.key] || [];
      const solved = pokemonForComparison && pageGuesses.some(g => g.name === pokemonForComparison.name);
      return { key: p.key, label: p.label, daily, solved, guessCount: solved ? pageGuesses.length : null };
    });
  }, [pokemonData, yesterdayGuessesByPage, yesterdayDate, getCardAnswerForDate, selectPokemonForDate]);

  const yesterdayDailyByPage = useMemo(() => {
    const map = {};
    yesterdayPerPageResults.forEach(r => { map[r.key] = r.daily || null; });
    return map;
  }, [yesterdayPerPageResults]);

  // Console-log a compact summary of the selected pokemon for debugging/visibility
  useEffect(() => {
    if (!perPageResults || perPageResults.length === 0) return;
    // Only log in development to avoid noisy production consoles
    if (typeof process !== 'undefined' && process.env && process.env.NODE_ENV === 'production') return;
    try {
      const summary = perPageResults.map(r => {
        const base = { key: r.key, solved: !!r.solved, guessCount: r.guessCount ?? null };
        if (!r.daily) return { ...base, id: null, name: null };
        // Card page returns an object { pokemon, card }
        if (r.key === 'card' && r.daily.pokemon) {
          return {
            ...base,
            id: r.daily.pokemon.id ?? null,
            name: r.daily.pokemon.name ?? null,
            cardFile: r.daily.card?.cardFile ?? null,
            cardType: r.daily.card?.cardType ?? r.daily.card?.card_type ?? null,
          };
        }
        return { ...base, id: r.daily.id ?? null, name: r.daily.name ?? null };
      });
      //console.log('Pokedle per-page daily selection:', summary);
      //console.log('Pokedle dailyByPage map:', dailyByPage);
    } catch (e) {
      if (typeof console !== 'undefined') console.log('Error logging perPageResults', e);
    }
  }, [perPageResults, dailyByPage]);

  // Persist a simple daily summary (scores per mode) into localStorage so previous
  // days' results can be inspected later. We store an array of { date, results }
  // where `date` is the YYYYMMDD integer seed and `results` is an array of
  // { key, label, solved, guessCount } for that day.
  useEffect(() => {
    try {
      if (!perPageResults || perPageResults.length === 0) return;
      const key = 'pokedle_results_history';
      const todaySeed = getSeedFromDate(new Date());
      const entry = {
        date: todaySeed,
        results: perPageResults.map(r => ({ key: r.key, label: r.label, solved: !!r.solved, guessCount: r.solved ? r.guessCount : null }))
      };
      const raw = localStorage.getItem(key);
      const history = raw ? JSON.parse(raw) : [];
      // If last entry is for today, update it; otherwise append a new entry
      if (history.length > 0 && history[history.length - 1].date === todaySeed) {
        history[history.length - 1] = entry;
      } else {
        history.push(entry);
      }
      localStorage.setItem(key, JSON.stringify(history));
    } catch (e) {
      // ignore storage errors
    }
  }, [perPageResults]);

  // Preload common images (sprites, full image, silhouette) for each selected daily pokemon
  useEffect(() => {
    if (!perPageResults || perPageResults.length === 0) return;
    const imgs = [];
    try {
      const pushed = new Set();
      perPageResults.forEach(r => {
        const p = r.daily;
        if (!p) return;
        // if card page, r.daily may be { pokemon, card }
        const pokemonObj = p.pokemon ? p.pokemon : p;
        if (pokemonObj && pokemonObj.id) {
          const id = pokemonObj.id;
          const candidates = [
            `https://raw.githubusercontent.com/Pythagean/pokedle_assets/main/sprites_trimmed/${id}-front.png`,
            `https://raw.githubusercontent.com/Pythagean/pokedle_assets/main/images/${id}.png`,
            `https://raw.githubusercontent.com/Pythagean/pokedle_assets/main/silhouettes/${id}.png`,
            `https://raw.githubusercontent.com/Pythagean/pokedle_assets/main/colours/sprite/${id}.png`
          ];
          candidates.forEach(u => {
            if (!pushed.has(u)) {
              pushed.add(u);
              const img = new Image();
              img.src = u;
              imgs.push(img);
            }
          });
        }
        // Preload card images if provided
        if (p.card) {
          const cp = p.card;
          const cardUrls = [];
          if (cp.resized) cardUrls.push(cp.resized);
          if (cp.cropped) cardUrls.push(cp.cropped);
          cardUrls.forEach(u => {
            if (!pushed.has(u)) {
              pushed.add(u);
              const img = new Image();
              img.src = u;
              imgs.push(img);
            }
          });
        }
      });
    } catch (e) {
      // ignore
    }
    return () => { imgs.length = 0; };
  }, [perPageResults]);

  const allCompleted = perPageResults.length > 0 && perPageResults.every(r => r.solved);

  // Transient highlight flag: becomes true briefly when allCompleted transitions false->true
  const [completionJustCompleted, setCompletionJustCompleted] = useState(false);
  const prevAllCompletedRef = useRef(!!allCompleted);
  useEffect(() => {
    const prev = prevAllCompletedRef.current;
    if (!prev && allCompleted) {
      setCompletionJustCompleted(true);
      const t = setTimeout(() => setCompletionJustCompleted(false), 6000);
      return () => clearTimeout(t);
    }
    prevAllCompletedRef.current = allCompleted;
  }, [allCompleted]);

  // Submit result to Supabase once all modes are completed for the day
  useEffect(() => {
    if (!allCompleted) return;
    const todaySeed = getSeedFromDate(new Date());
    submitResult({ perPageResults, guessesByPage, todaySeed });
  }, [allCompleted, perPageResults, guessesByPage]);

  if (!pokemonData) return <div>Loading data...</div>;

  // Helper to get/set guesses for current page
  const guesses = guessesByPage[page] || [];
  const setGuesses = (newGuesses) => {
    setGuessesByPage(g => ({ ...g, [page]: newGuesses }));
  };

  // (perPageResults, allCompleted, and completionOpen are declared earlier so
  // hooks run in a stable order regardless of data-loading state)

  // Comparison logic for feedback
  function getComparison(guessPoke, answerPoke) {
    if (!guessPoke || !answerPoke) return {};
    // Helper for partial match (e.g. one type matches)
    function partialMatch(arr1, arr2) {
      return arr1.some(item => arr2.includes(item));
    }
    // Evolution stage: fallback to 1 if not present
    const getEvoStage = poke => poke.evolution_stage || 1;
    const guessEvo = getEvoStage(guessPoke);
    const answerEvo = getEvoStage(answerPoke);
    return {
      name: guessPoke.name === answerPoke.name ? 'match' : 'miss',
      color: (guessPoke.main_colour || guessPoke.color) === (answerPoke.main_colour || answerPoke.color) ? 'match' : 'miss',
      types: JSON.stringify(guessPoke.types) === JSON.stringify(answerPoke.types)
        ? 'match'
        : (partialMatch(guessPoke.types, answerPoke.types) ? 'partial' : 'miss'),
      habitat: guessPoke.habitat === answerPoke.habitat ? 'match' : 'miss',
      height: guessPoke.height === answerPoke.height ? 'match' : (guessPoke.height > answerPoke.height ? 'down' : 'up'),
      weight: guessPoke.weight === answerPoke.weight ? 'match' : (guessPoke.weight > answerPoke.weight ? 'down' : 'up'),
      evolution: guessEvo === answerEvo ? 'match' : (guessEvo > answerEvo ? 'down' : 'up'),
    };
  }

  // Render a page component by key (keeps JSX mapping in one place)
  function renderPageByKey(key) {
    const activeDaily = yesterdayMode ? yesterdayDailyByPage : dailyByPage;
    const activeGuesses = yesterdayMode ? yesterdayGuessesByPage : guessesByPage;
    const setActiveGuesses = yesterdayMode
      ? (pageKey, newGuesses) => setYesterdayGuessesByPage(g => ({ ...g, [pageKey]: newGuesses }))
      : (pageKey, newGuesses) => setGuessesByPage(g => ({ ...g, [pageKey]: newGuesses }));

    if (key === 'classic') return <ClassicPage pokemonData={pokemonData} daily={activeDaily.classic} guesses={activeGuesses.classic} setGuesses={newGuesses => setActiveGuesses('classic', newGuesses)} useShinySprites={false} />;
    if (key === 'pokedex') return <PokedexPage pokemonData={pokemonData} daily={activeDaily.pokedex} guesses={activeGuesses.pokedex} setGuesses={newGuesses => setActiveGuesses('pokedex', newGuesses)} />;
    if (key === 'stats') return <StatsPage pokemonData={pokemonData} guesses={guessesByPage.stats} setGuesses={newGuesses => setGuessesByPage(g => ({ ...g, stats: newGuesses }))} />;
    if (key === 'ability') return <AbilityPage pokemonData={pokemonData} guesses={guessesByPage.ability} setGuesses={newGuesses => setGuessesByPage(g => ({ ...g, ability: newGuesses }))} />;
    if (key === 'moves') return <MovesPage pokemonData={pokemonData} guesses={guessesByPage.moves} setGuesses={newGuesses => setGuessesByPage(g => ({ ...g, moves: newGuesses }))} useShinySprites={false} />;
    if (key === 'category') return <CategoryPage pokemonData={pokemonData} guesses={guessesByPage.category} setGuesses={newGuesses => setGuessesByPage(g => ({ ...g, category: newGuesses }))} useShinySprites={false} />;
    if (key === 'details') {
      const detailsMode = yesterdayMode ? getDetailsModeForDate(yesterdayDate) : getDetailsModeForDate(new Date());
      if (detailsMode === 'silhouette') {
        return <SilhouettePage pokemonData={pokemonData} silhouetteMeta={silhouetteMeta} daily={activeDaily.details} guesses={activeGuesses.details || []} setGuesses={newGuesses => setActiveGuesses('details', newGuesses)} useShinySprites={false} />;
      } else if (detailsMode === 'zoom') {
        return <ZoomPage pokemonData={pokemonData} zoomMeta={zoomMeta} daily={activeDaily.details} guesses={activeGuesses.details || []} setGuesses={newGuesses => setActiveGuesses('details', newGuesses)} useShinySprites={false} />;
      } else {
        return <EyesPage pokemonData={pokemonData} daily={activeDaily.details} guesses={activeGuesses.details || []} setGuesses={newGuesses => setActiveGuesses('details', newGuesses)} bodyPartsManifest={bodyPartsManifest} useShinySprites={false} />;
      }
    }
    if (key === 'colours') return <ColoursPage pokemonData={pokemonData} daily={activeDaily.colours} guesses={activeGuesses.colours} setGuesses={newGuesses => setActiveGuesses('colours', newGuesses)} useShinySprites={false} />;
    if (key === 'locations') return <LocationsPage pokemonData={pokemonData} guesses={guessesByPage.locations} setGuesses={newGuesses => setGuessesByPage(g => ({ ...g, locations: newGuesses }))} useShinySprites={false} />;
    if (key === 'card') return <CardPage pokemonData={pokemonData} daily={activeDaily.card} guesses={activeGuesses.card} setGuesses={newGuesses => setActiveGuesses('card', newGuesses)} useShinySprites={activeDaily?.card?.card?.cardType === 'shiny'} />;
    if (key === 'map') return <LocationsPage pokemonData={pokemonData} daily={activeDaily.map} guesses={activeGuesses.map || []} setGuesses={newGuesses => setActiveGuesses('map', newGuesses)} useShinySprites={false} />;
    if (key === 'results') return <ResultsPage results={yesterdayMode ? yesterdayPerPageResults : perPageResults} guessesByPage={activeGuesses} onBack={() => setPage('classic')} backgroundsManifest={backgroundsManifest} date={yesterdayMode ? yesterdayDate : undefined} />;
    if (key === 'patchnotes') return <PatchNotesPage />;
    if (key === 'about') return <AboutPage onPrivacyClick={() => setPage('privacy')} setPage={setPage} />;
    if (key === 'privacy') return <PrivacyPolicyPage onBack={() => setPage('about')} />;
    return null;
  }

  return (
    <>
      {/* Fixed header at top-level so it never scrolls with content */}
      <style>{`
        .main-app {
          max-width: 900px;
          margin: 0 auto;
          padding: 80px 20px 24px 20px;
          font-family: 'Inter', Arial, sans-serif;
          box-sizing: border-box;
          display: flex;
          flex-direction: column;
          align-items: stretch;
          justify-content: flex-start;
          min-height: calc(100vh - 80px);
          touch-action: pan-y;
        }
        
        @media (max-width: 600px) {
          .main-app {
            padding: 50px 8px 24px 8px;
            min-height: calc(100vh - 80px);
          }
        }
      `}</style>
      {
        (() => {
          const completedPages = (yesterdayMode ? yesterdayPerPageResults : perPageResults).reduce((acc, r) => ({ ...acc, [r.key]: !!r.solved }), {});
          return <Header pages={PAGES} page={page} setPage={setPage} titleImg={titleImg} showCompletionButton={allCompleted} onCompletionClick={() => setPage('results')} highlightCompletion={completionJustCompleted} completionActive={page === 'results'} completedPages={completedPages} compactNav={compactNav} onMenuClick={() => setMenuOpen(o => !o)} menuOpen={menuOpen} onPatchNotesClick={() => setPage('patchnotes')} onAboutClick={() => setPage('about')} onYesterdayClick={() => { setYesterdayMode(true); setMenuOpen(false); }} yesterdayMode={yesterdayMode} />;
        })()
      }
      {/* Page Content - separate scrollable container so header stays fixed */}
        <div
          className="main-app"
          ref={mainAppRef}
        >
          {yesterdayMode && (
            <div style={{ background: '#fff3cd', border: '1px solid #ffc107', borderRadius: 8, padding: '8px 16px', marginBottom: 16, display: 'flex', alignItems: 'center', justifyContent: 'space-between', fontSize: 14 }}>
              <span>📅 Viewing <strong>Yesterday's Pokédle</strong></span>
              <button onClick={() => setYesterdayMode(false)} style={{ background: 'none', border: 'none', color: '#1976d2', fontWeight: 600, cursor: 'pointer', fontSize: 14 }}>Back to Today</button>
            </div>
          )}
          {/* Debug Panel
          <div style={{
            marginBottom: '20px',
            padding: '12px',
            background: '#f0f0f0',
            borderRadius: '8px',
            border: '2px solid #ddd'
          }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: debugPanelOpen ? '12px' : '0' }}>
              <strong style={{ fontSize: '14px' }}>🐛 Debug Mode</strong>
              <button
                onClick={() => setDebugPanelOpen(!debugPanelOpen)}
                style={{
                  padding: '4px 12px',
                  background: '#fff',
                  border: '1px solid #ccc',
                  borderRadius: '4px',
                  cursor: 'pointer',
                  fontSize: '12px'
                }}
              >
                {debugPanelOpen ? 'Hide' : 'Show'}
              </button>
            </div>
            
            {debugPanelOpen && (
              <div>
                <div style={{ marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' }}>
                  <label style={{ fontSize: '13px', fontWeight: '500' }}>Day Offset:</label>
                  <select
                    value={debugDayOffset}
                    onChange={(e) => setDebugDayOffset(parseInt(e.target.value, 10))}
                    style={{
                      padding: '6px 10px',
                      borderRadius: '4px',
                      border: '1px solid #ccc',
                      fontSize: '13px',
                      background: '#fff'
                    }}
                  >
                    {[-28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0].map(offset => {
                      const testDate = new Date();
                      testDate.setDate(testDate.getDate() + offset);
                      const dayName = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'][testDate.getDay()];
                      const dateStr = testDate.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
                      return (
                        <option key={offset} value={offset}>
                          {offset === 0 ? 'Today' : `${offset} days`} ({dayName} {dateStr})
                        </option>
                      );
                    })}
                  </select>
                  <span style={{ fontSize: '12px', color: '#666', marginLeft: '8px' }}>
                    Seed: {getSeedFromDate(today)}
                  </span>
                </div>
                
                <div style={{ 
                  marginBottom: '12px', 
                  padding: '8px', 
                  background: '#f8f9fa', 
                  borderRadius: '4px',
                  fontSize: '11px',
                  display: 'flex',
                  gap: '16px',
                  flexWrap: 'wrap',
                  alignItems: 'center'
                }}>
                  <div><strong>Legend:</strong></div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                    <span style={{ display: 'inline-block', width: '16px', height: '16px', background: '#fff3cd', border: '1px solid #ccc' }}></span>
                    <span>Selected Day</span>
                  </div>
                  <div style={{ fontSize: '10px', color: '#666', fontStyle: 'italic' }}>
                    Note: Grid shows selections with anti-repeat logic (no Pokemon repeats within 28 days per mode)
                  </div>
                </div>
                
                <div style={{ 
                  background: '#fff', 
                  padding: '10px', 
                  borderRadius: '4px',
                  fontSize: '11px',
                  maxHeight: '500px',
                  overflowY: 'auto',
                  overflowX: 'auto'
                }}>
                  <div style={{ fontWeight: 'bold', marginBottom: '8px', fontSize: '13px' }}>
                    Pokemon Selection Grid (Dates × Modes):
                  </div>
                  <table style={{ 
                    borderCollapse: 'collapse',
                    fontSize: '11px',
                    minWidth: '100%'
                  }}>
                    <thead>
                      <tr style={{ background: '#f8f9fa', borderBottom: '2px solid #dee2e6' }}>
                        <th style={{ 
                          padding: '8px', 
                          textAlign: 'left', 
                          fontWeight: '600',
                          position: 'sticky',
                          left: 0,
                          background: '#f8f9fa',
                          zIndex: 1,
                          minWidth: '80px'
                        }}>
                          Mode
                        </th>
                        {[-28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0].map(offset => {
                          const testDate = new Date();
                          testDate.setDate(testDate.getDate() + offset);
                          const dayName = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'][testDate.getDay()];
                          const dateStr = testDate.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
                          return (
                            <th key={offset} style={{ 
                              padding: '6px 8px', 
                              textAlign: 'center', 
                              fontWeight: '600',
                              minWidth: '85px',
                              fontSize: '10px',
                              background: offset === debugDayOffset ? '#fff3cd' : '#f8f9fa'
                            }}>
                              <div>{dayName}</div>
                              <div style={{ fontWeight: '400', color: '#666' }}>{dateStr}</div>
                            </th>
                          );
                        })}
                      </tr>
                    </thead>
                    <tbody>
                      {PAGES.filter(p => p.key !== 'results').map(pageInfo => {
                        return (
                          <tr key={pageInfo.key} style={{ borderBottom: '1px solid #eee' }}>
                            <td style={{ 
                              padding: '8px',
                              fontWeight: '500',
                              position: 'sticky',
                              left: 0,
                              background: '#fff',
                              zIndex: 1,
                              borderRight: '1px solid #ddd'
                            }}>
                              {pageInfo.label}
                            </td>
                            {[-28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0].map(offset => {
                              // Calculate Pokemon for this date and mode using the exact same selection logic
                              const testDate = new Date();
                              testDate.setDate(testDate.getDate() + offset);
                              
                              // Use the helper function to get the actual Pokemon that would be selected
                              const pokemon = selectPokemonForDate(testDate, pageInfo.key);
                              
                              const isHighlighted = offset === debugDayOffset;
                              
                              return (
                                <td key={offset} style={{ 
                                  padding: '6px 8px',
                                  textAlign: 'center',
                                  fontFamily: 'monospace',
                                  fontSize: '10px',
                                  background: isHighlighted ? '#fff3cd' : '#fff',
                                  borderLeft: '1px solid #f0f0f0',
                                  position: 'relative'
                                }}>
                                  {pokemon ? (
                                    <>
                                      <div style={{ fontWeight: '500' }}>#{pokemon.id}</div>
                                      <div style={{ color: '#666', fontSize: '9px' }}>{pokemon.name}</div>
                                    </>
                                  ) : (
                                    <div style={{ color: '#999', fontSize: '9px' }}>N/A</div>
                                  )}
                                </td>
                              );
                            })}
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </div> */}
          
          {/* Themed day banner */}
          {todayTheme && (
            <div style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: 10,
              padding: '8px 18px',
              marginBottom: 8,
              marginTop: 8,
              borderRadius: 10,
              background: 'linear-gradient(90deg, #fffde7 0%, #fff9c4 100%)',
              border: '1.5px solid #f9c74f',
              boxShadow: '0 2px 8px rgba(249,199,79,0.18)',
              fontSize: 16,
              fontWeight: 600,
              color: '#5a4800',
              textAlign: 'center',
            }}>
              <span style={{ fontSize: 22 }}>✨</span>
              <span>Today's Pokédle has a theme!</span>
              <span style={{ fontSize: 22 }}>✨</span>
            </div>
          )}
          {/* Page Content */}
          {!pageTransition && renderPageByKey(page)}
          {pageTransition && (
            <div style={{ position: 'relative', width: '100%', overflow: 'hidden' }}>
              <div
                style={{
                  display: 'flex',
                  width: '200%',
                  transition: 'transform 360ms cubic-bezier(.2,.8,.2,1)',
                  transform: pageTransition.animate
                    ? (pageTransition.direction === 'left' ? 'translateX(-50%)' : 'translateX(0%)')
                    : (pageTransition.direction === 'left' ? 'translateX(0%)' : 'translateX(-50%)')
                }}
                onTransitionEnd={() => {
                  // commit the page change and clear transition state
                  setPage(pageTransition.to);
                  setPageTransition(null);
                }}
              >
                {/* Order the slides so animation direction matches visual motion */}
                {pageTransition.direction === 'left' ? (
                  <>
                    <div style={{ width: '50%' }}>{renderPageByKey(pageTransition.from)}</div>
                    <div style={{ width: '50%' }}>{renderPageByKey(pageTransition.to)}</div>
                  </>
                ) : (
                  <>
                    <div style={{ width: '50%' }}>{renderPageByKey(pageTransition.to)}</div>
                    <div style={{ width: '50%' }}>{renderPageByKey(pageTransition.from)}</div>
                  </>
                )}
              </div>
            </div>
          )}
      </div>
      {/* Results page is reachable via the main navigation (PAGES). */}
    </>
  );
}
export default App;